CONTAINER AINODE_JF_NESTED_DIELECTRIC
{
   	NAME ainode_jf_nested_dielectric;

   	INCLUDE GVbase;

   	GROUP C4DAI_JF_NESTED_DIELECTRIC_MAIN_GRP
   	{
      		DEFAULT 1;

		GROUP C4DAI_JF_NESTED_DIELECTRIC_BASIC_DIELECTRIC_PROPERTIES_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_MEDIUMPRIORITY {}
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_MEDIUMIOR {}
			GROUP C4DAI_JF_NESTED_DIELECTRIC_TRANSMISSION_GRP
		{
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_MEDIUMTRANSMITTANCE {}
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_MEDIUMTRANSMITTANCE_SCALE {}
		}

		GROUP C4DAI_JF_NESTED_DIELECTRIC_POLARIZING_FILTER_GRP
		{
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_POLARIZE {}
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_POLARIZATION_ANGLE {}
		}

		}
		
	GROUP C4DAI_JF_NESTED_DIELECTRIC_REFRACTION_GRP
	{
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFRACTION_SCALE {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_BTDF {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFRACTION_ROUGHNESS_U {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFRACTION_ROUGHNESS_V {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_INDIRECT_REFRACTION {}
		GROUP C4DAI_JF_NESTED_DIELECTRIC_DIRECT_REFRACTION_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DIRECT_REFRACTION {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_USE_REFRACTION_BTDF {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_ROUGHNESSOFFSET {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_ROUGHNESSDEPTHMULTIPLIER {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_ROUGHNESSDEPTHADDER {}
		}

		GROUP C4DAI_JF_NESTED_DIELECTRIC_DIRECT_REFRACTION_MANUAL_BTDF_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_BTDF {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_ROUGHNESS_U {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_ROUGHNESS_V {}
		}

		GROUP C4DAI_JF_NESTED_DIELECTRIC_DIRECT_REFRACTION_SECOND_LOBE_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_SECOND_SCALE {}
      			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DR_SECOND_ROUGHNESSMULTIPLIER {}
		}
		
		}


	GROUP C4DAI_JF_NESTED_DIELECTRIC_DISPERSION_GRP
	{
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DISPERSE {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DISPERSION {}
		GROUP C4DAIP_JF_NESTED_DIELECTRIC_SPECTRAL_CONVERSION_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECTRAL_DISTRIBUTION {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECTRAL_GAMUT {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECTRAL_CLAMP_NEGATIVE_COLORS {}
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECTRAL_SATURATION {}
		}

		}

	GROUP C4DAIP_JF_NESTED_DIELECTRIC_SPECULAR_GRP
	{
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECULAR_SCALE {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_BRDF {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_DIRECT_SPECULAR {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_INDIRECT_SPECULAR {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECULAR_ROUGHNESS_U {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECULAR_ROUGHNESS_V {}
		GROUP C4DAIP_JF_NESTED_DIELECTRIC_COMPONENTS_GRP
		{
			AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SPECULAR_RAY_TYPE {}
		}

	GROUP C4DAIP_JF_NESTED_DIELECTRIC_OPTIMIZATION_GRP
	{
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_ENABLE_INTERNAL_REFLECTIONS {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_RUSSIAN_ROULETTE_PROBABILITY {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_ENERGY_CUTOFF_EXPONENT {}
	}

	
      	GROUP C4DAIP_JF_NESTED_DIELECTRIC_ANISOTROPY_GRP
	{
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_BLUR_ANISOTROPIC_POLES {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_WARD_TANGENT {}
	}

	}

	GROUP C4DAIP_JF_NESTED_DIELECTRIC_SKY_BEVAVIOURS_GRP
	{
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFRACT_SKYDOMES {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFRACT_SKIES {}	
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFLECT_SKYDOMES {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_REFLECT_SKIES {}
	}

	GROUP C4DAIP_JF_NESTED_DIELECTRIC_EMISSION_GRP
	{
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_EMISSION_AT_INTERFACES {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_EMISSION_AT_EXITS {}
		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_EMISSION_AT_ENTRANCES {}	
	}

	GROUP C4DAIP_JF_NESTED_SHADOWS_AND_CAUSTICS_GRP
	{
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_SHADOW_MODE {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_MODE {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_REFRACTIONS_DIRECT {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_DR_ROUGHNESS_OFFSET {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_REFRACTIONS_INDIRECT {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_TIR {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_INTERNAL_SPECULARS {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_DISPERSION {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_SPECULAR_DIRECT {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_SPECULAR_INDIRECT {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_CAUSTIC_MAX_DISTANCE {}
	}

	GROUP C4DAIP_JF_NESTED_AOVS_GRP
	{
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_AOV_DIRECT_REFRACTION {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_AOV_INDIRECT_REFRACTION {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_AOV_DIRECT_SPECULAR {}
      		AIPARAM C4DAIP_JF_NESTED_DIELECTRIC_AOV_INDIRECT_SPECULAR {}

	}
   }
}

